PseudoRCTC/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('book.urls')),
]

book/urls.py
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    path('',views.homeView,name="home"),
    path('search',views.searchView,name="search"),
    path('complexSearch/<source>-<dest>/<date>',views.complexSearchView,name="complexSearch"),
    path('mapSearch>',views.MapSearchView.as_view(),name="mapSearch"),
    path('book/<chart>/<sourceSchedule>-<destSchedule>/<type>/<date>',views.bookView,name="book"),
    path('book/<chart1>-<chart2>/<sourceSchedule>-<commonSchedule1>/<commonSchedule2>-<destSchedule>/<type>/<date>',views.complexBookView,name="complexBook"),
    path('confirm/<chart>/<sourceSchedule>-<destSchedule>/<type>/<date>',views.confirmTicketView,name="confirm"),
    path('confirm/<chart1>-<chart2>/<sourceSchedule>-<commonSchedule1>/<commonSchedule2>-<destSchedule>/<type>/<date>',views.complexConfirmTicketView,name="complexConfirm"),
    path('profile', views.profileView, name="profile"),
    path('cancel/<pk>', views.cancelTicket.as_view(), name="cancel"),


]

book/models.py
from django.db import models
from django.contrib.auth import get_user_model

User= get_user_model()


# Create your models here.

class Station(models.Model):
    state = models.CharField("State",max_length=20, null=True)
    code = models.CharField("Code",max_length=10,primary_key=True)
    name = models.CharField("Name",max_length=30)
    zone = models.CharField("Zone",max_length=10, null=True)
    address = models.CharField("Address",max_length=50, null=True)

    def __str__(self):
        return self.name

class Train(models.Model):
    arrival = models.CharField("Arrival",max_length=8, null=True)
    source = models.ForeignKey(Station, on_delete=models.SET(None), related_name="train_source")
    name = models.CharField("Name", max_length=30)
    zone = models.CharField("Zone", max_length=10, null=True)
    number = models.CharField("Number", max_length=15,primary_key=True)
    departure = models.CharField("Departure",max_length=8, null=True)
    return_train = models.CharField("Return Train",max_length=15, null=True)
    dest = models.ForeignKey(Station, on_delete=models.SET(None), related_name="train_dest")
    duration_h = models.IntegerField("Duration Hours", null=True)
    duration_m = models.IntegerField("Duration Minutes", null=True)
    type = models.CharField("Type",max_length=5, null=True)
    distance = models.IntegerField("Distance", null=True)

    def __str__(self):
        return self.name


class Schedule(models.Model):
    arrival = models.CharField("Arrival", max_length=8, null=True)
    day = models.IntegerField("Day", null=True)
    train = models.ForeignKey(Train, on_delete=models.CASCADE, related_name="train_schedule")
    station = models.ForeignKey(Station, on_delete=models.CASCADE, related_name="station_schedule")
    id = models.IntegerField("id",primary_key=True)
    departure = models.CharField("Departure", max_length=8, null=True)

    def __str__(self):
        return str(self.train) +" at "+str(self.station)


class Seat_Chart(models.Model):
    train = models.ForeignKey(Train, on_delete=models.CASCADE, related_name="train_chart")
    first_ac = models.IntegerField("1st AC")
    second_ac = models.IntegerField("2nd AC")
    third_ac = models.IntegerField("3rd AC")
    sleeper = models.IntegerField("Sleeper")
    date = models.DateField("Date")

    def get1A(self):
        return self.first_ac - self.chart_tickets.all().filter(type="1A").count()

    def get2A(self):
        return self.second_ac - self.chart_tickets.all().filter(type="2A").count()

    def get3A(self):
        return self.third_ac - self.chart_tickets.all().filter(type="3A").count()

    def getSL(self):
        return self.sleeper - self.chart_tickets.all().filter(type="SL").count()

    def __str__(self):
        return str(self.train) +" on "+str(self.date)

class Ticket(models.Model):
    passenger = models.CharField("Name",max_length=20)
    train = models.ForeignKey(Train, on_delete=models.CASCADE, related_name="train_tickets")
    type = models.CharField("Type",max_length=2)
    chart = models.ForeignKey(Seat_Chart, on_delete=models.CASCADE, related_name="chart_tickets")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="tickets")
    source = models.ForeignKey(Station, on_delete=models.CASCADE, related_name="source_tickets")
    dest = models.ForeignKey(Station, on_delete=models.CASCADE, related_name="dest_tickets")
    source_schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, related_name="source_schedule_tickets")
    dest_schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, related_name="dest_schedule_tickets")
    date = models.DateField("Date")
    fare = models.IntegerField("Fare")

    def __str__(self):
        return str(self.passenger) +" on "+str(self.date)+" in "+str(self.train)

    def calculateFare(self):
        factor=1
        if(self.type=="1A"):
            factor=20
        elif(self.type=="2A"):
            factor=15
        elif (self.type == "3A"):
            factor = 10
        else:
            factor = 5
        self.fare = (self.dest_schedule.pk - self.source_schedule.pk)*factor

book/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView,UpdateView,DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import authentication, permissions
from rest_framework.views import APIView
from rest_framework.response import Response
from .models import *
from dateutil import parser
import json, time

# Create your views here.

@login_required(login_url="/login")
def homeView(request):
    stations=Station.objects.all()
    context={
        "stations" : stations,
        "st" : stations[0:4]
    }
    return render(request,'book/home.html',context)

@login_required(login_url="/login")
def searchView(request):
    source = Station.objects.get(pk=request.POST['source'])
    dest = Station.objects.get(pk=request.POST['dest'])
    date = request.POST['journey_date']
    sourceTrains = []
    for s in source.station_schedule.all():
        sourceTrains.append(s.train)
    destTrains = []
    for s in dest.station_schedule.all():
        destTrains.append(s.train)
    allTrains=list(set(sourceTrains) & set(destTrains))


    trains=[]
    sourceSchedules=[]
    destSchedules=[]
    scheduleCharts=[]
    fares=[]
    for t in allTrains:
        departing_station = t.train_schedule.get(station=source)
        arriving_station = t.train_schedule.get(station=dest)
        if departing_station.pk < arriving_station.pk:
            scheduleCharts.append(Seat_Chart.objects.get(date=parser.parse(date),train=t))
            trains.append(t)
            sourceSchedules.append(departing_station)
            destSchedules.append(arriving_station)
            fare={}
            fare["1A"]=(arriving_station.pk - departing_station.pk)*20
            fare["2A"]=(arriving_station.pk - departing_station.pk)*15
            fare["3A"]=(arriving_station.pk - departing_station.pk)*10
            fare["SL"]=(arriving_station.pk - departing_station.pk)*5
            fares.append((fare))

    schedules=zip(trains,sourceSchedules,destSchedules,scheduleCharts,fares)
    data={
        "source": source,
        "dest": dest,
        "schedules":schedules,
        "date": date,
    }
    return render(request,'book/trainSearch.html',data)

@login_required(login_url="/login")
def complexSearchView(request,source,dest,date):
    source = Station.objects.get(pk=source)
    dest = Station.objects.get(pk=dest)
    sourceTrains = []
    for s in source.station_schedule.all():
        sourceTrains.append(s.train)
    destTrains = []
    for s in dest.station_schedule.all():
        destTrains.append(s.train)
    # allTrains=list(set(sourceTrains) & set(destTrains))

    trains1 = []
    trains2 = []
    sourceSchedules = []
    commonSchedules1 = []
    commonSchedules2 = []
    destSchedules = []
    scheduleCharts1 = []
    scheduleCharts2 = []
    fares=[]


    for ts in sourceTrains:
        sourceSchedule=source.station_schedule.get(train=ts)
        source_stations = []
        for a in ts.train_schedule.filter(id__gte=sourceSchedule.id):
            source_stations.append(a.station)
        for td in destTrains:
            destSchedule = dest.station_schedule.get(train=td)
            dest_stations = []
            for a in td.train_schedule.filter(id__lte=destSchedule.id):
                dest_stations.append(a.station)
            common = list(set(source_stations) & set(dest_stations))
            for c in common:
                tempDestSchedule=c.station_schedule.get(train=ts)
                tempSourceSchedule=c.station_schedule.get(train=td)
                if(tempDestSchedule.arrival < tempSourceSchedule.departure):
                    trains1.append(ts)
                    trains2.append(td)
                    commonSchedules1.append(tempDestSchedule)
                    commonSchedules2.append(tempSourceSchedule)
                    sourceSchedules.append(sourceSchedule)
                    destSchedules.append(destSchedule)
                    c1=Seat_Chart.objects.get(date=parser.parse(date),train=ts)
                    c2=Seat_Chart.objects.get(date=parser.parse(date),train=td)
                    scheduleCharts1.append(c1)
                    scheduleCharts2.append(c2)
                    # fares.append(None)
                    fare = {}
                    fare["1A"] = (destSchedule.pk - tempSourceSchedule.pk + tempDestSchedule.pk - sourceSchedule.pk) * 20
                    fare["2A"] = (destSchedule.pk - tempSourceSchedule.pk + tempDestSchedule.pk - sourceSchedule.pk) * 15
                    fare["3A"] = (destSchedule.pk - tempSourceSchedule.pk + tempDestSchedule.pk - sourceSchedule.pk) * 10
                    fare["SL"] = (destSchedule.pk - tempSourceSchedule.pk + tempDestSchedule.pk - sourceSchedule.pk) * 5
                    fares.append((fare))
                    break

    schedules=zip(trains1,trains2,sourceSchedules,commonSchedules1,commonSchedules2,destSchedules,scheduleCharts1,scheduleCharts2,fares)
    data={
        "source": source,
        "dest": dest,
        "schedules":schedules,
        "date": date,
    }
    return render(request,'book/connectingTrainSearch.html',data)


class MapSearchView(LoginRequiredMixin, APIView):
    login_url =  '/login'
    authentication_classes = (authentication.SessionAuthentication,)
    permission_classes = (permissions.IsAuthenticated,)

    def get(self, request, format=None):
        date=request.GET["date"]
        sources = request.GET["source"]
        dests = request.GET["dest"]
        for s in sources:
            source=Station.objects.filter(name__iexact=sources)
            print(s)
            if source.count():
                break
        for d in dests:
            dest=Station.objects.filter(name__iexact=dests)
            if dest.count():
                break

        data={
            "date":date,
            "source":source[0].code,
            "dest": dest[0].code,
        }

        return Response(data)

@login_required(login_url="/login")
def bookView(request,chart,sourceSchedule,destSchedule,type,date):
    chart = Seat_Chart.objects.get(pk=chart)
    train = chart.train
    sourceSchedule=Schedule.objects.get(pk=sourceSchedule)
    destSchedule=Schedule.objects.get(pk=destSchedule)
    source = sourceSchedule.station
    dest = destSchedule.station
    data = {
        "train": train,
        "chart": chart,
        "sourceSchedule": sourceSchedule,
        "destSchedule": destSchedule,
        "source":source,
        "dest":dest,
        "type":type,
        "date":date,
    }
    return render(request,'book/booking.html',data)

@login_required(login_url="/login")
def complexBookView(request,chart1,chart2,sourceSchedule,commonSchedule1,commonSchedule2,destSchedule,type,date):
    chart1 = Seat_Chart.objects.get(pk=chart1)
    chart2 = Seat_Chart.objects.get(pk=chart2)
    train1 = chart1.train
    train2 = chart2.train
    sourceSchedule=Schedule.objects.get(pk=sourceSchedule)
    commonSchedule1=Schedule.objects.get(pk=commonSchedule1)
    commonSchedule2=Schedule.objects.get(pk=commonSchedule2)
    destSchedule=Schedule.objects.get(pk=destSchedule)
    source = sourceSchedule.station
    dest = destSchedule.station
    data = {
        "train1": train1,
        "train2": train2,
        "chart1": chart1,
        "chart2": chart2,
        "sourceSchedule": sourceSchedule,
        "commonSchedule1": commonSchedule1,
        "commonSchedule2": commonSchedule2,
        "destSchedule": destSchedule,
        "source":source,
        "dest":dest,
        "type":type,
        "date":date,
    }
    return render(request,'book/complexBooking.html',data)

@login_required(login_url="/login")
def confirmTicketView(request,chart,sourceSchedule,destSchedule,type,date):
    chart=Seat_Chart.objects.get(pk=chart)
    train=chart.train
    sourceSchedule=Schedule.objects.get(pk=sourceSchedule)
    destSchedule=Schedule.objects.get(pk=destSchedule)
    source = sourceSchedule.station
    dest = destSchedule.station
    user= request.user
    seats=int(request.POST["seats"])
    for i in range(seats):
        name=request.POST.get("name"+str(i))
        b=Ticket()
        b.passenger=name
        b.train=train
        b.type=type
        b.chart=chart
        b.user=user
        b.source=source
        b.dest=dest
        b.source_schedule=sourceSchedule
        b.dest_schedule=destSchedule
        b.date = date
        b.calculateFare()
        b.save()


    data = {
        "train": train,
        "sourceSchedule": sourceSchedule,
        "destSchedule": destSchedule,
        "source":source,
        "dest":dest,
        "type":type
    }
    return render(request, 'book/home.html')

@login_required(login_url="/login")
def complexConfirmTicketView(request,chart1,chart2,sourceSchedule,commonSchedule1,commonSchedule2,destSchedule,type,date):
    chart1 = Seat_Chart.objects.get(pk=chart1)
    chart2 = Seat_Chart.objects.get(pk=chart2)
    train1 = chart1.train
    train2 = chart2.train
    sourceSchedule = Schedule.objects.get(pk=sourceSchedule)
    commonSchedule1 = Schedule.objects.get(pk=commonSchedule1)
    commonSchedule2 = Schedule.objects.get(pk=commonSchedule2)
    destSchedule = Schedule.objects.get(pk=destSchedule)
    source = sourceSchedule.station
    dest = destSchedule.station
    user= request.user
    seats=int(request.POST["seats"])
    for i in range(seats):
        name=request.POST.get("name"+str(i))
        b=Ticket()
        b.passenger=name
        b.train=train1
        b.type=type
        b.chart=chart1
        b.user=user
        b.source=source
        b.dest=dest
        b.source_schedule=sourceSchedule
        b.dest_schedule=commonSchedule1
        b.date = date
        b.calculateFare()
        b.save()

        b = Ticket()
        b.passenger = name
        b.train = train2
        b.type = type
        b.chart = chart2
        b.user = user

templates/book/booking.html
{% extends "base.html" %}

{% block title %}{{ train }}/{{ source }}-{{ dest }}{% endblock %}

{% block body %}
    <div class="w3-display-middle" style="width:65%">
        <div class="w3-container w3-white w3-padding-16"  style="height: 500px; overflow-y: scroll;">
            <table style="width: 50%; margin: 0 25%;">
                <form action="{% url 'book:confirm' chart.pk sourceSchedule.pk destSchedule.pk type date %}" method="post" id="bookingForm">
                    {% csrf_token %}
                <tr><th>Train</th><td>{{ train }}</td></tr>
                <tr><th>From:</th><td>{{ source }} at {{ sourceSchedule.departure }}</td></tr>
                <tr><th>To:</th><td>{{ dest }} at {{ destSchedule.arrival }}</td></tr>
                <tr><th>Type:</th><td>{{ type }}</td></tr>
                <tr><th><label>Select no. of seats:</label></th>
                    <td><input class="seatsInput" type="number" name="seats" min="1" max="6" value="1" style="width: 10%;" onchange=createForm()>
                    <input type="Submit" class="w3-button w3-right confirmTicket" value="Confirm Ticket"></td>
                </tr>
            </table>
            <div class="w3-container col-lg-6" style="margin: 0 23%;">
                <table class="nameInputs">
                    <caption style="margin: 0 25%; width: 50%;">Passengers</caption>
                </table>
            </div>
            </form>

        </div>
    </div>

{% endblock %}

{% block end-scripts %}
    <script>
        $(document).ready(function(){
            i=0;
            input="<tr class='name" + i + "'><th>Passenger " + (i+1) +"</th><td><input type='text' name='name"+i+"' form='bookingForm' required></td></tr>";
            $(".nameInputs").append(input);
        });
        $(".seatsInput").focus();
        $(".confirmTicket").click(function () {
            seats=$(".seatsInput").val();

        })

        function createForm() {
            seats=$(".seatsInput").val();
            originalLength=$(".nameInputs").children().length-1;
            form=$(".nameInputs");
            if(originalLength>seats){
                for(i=seats;i<originalLength;i++){
                    $("tr").remove(".name"+i);
                }
            }
            for(i=originalLength;i<seats;i++){
                input="<tr class='name" + i + "'><th>Passenger " + (i+1) +"</th><td><input type='text' name='name"+i+"' form='bookingForm' required></td></tr>";
                $(".nameInputs").append(input);
            }

        }
    </script>
{% endblock %}

templates/book/home.html
{% extends "base.html" %}

{% block extra-head %}
<style type="text/css">
  #map{ width:700px; height: 500px; }
</style>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCFP-zJmSQLJLGdZyY5iWIumtJu7pdibAs&libraries=places"></script>
{% endblock %}

{% block title %}PseudoRCTC{% endblock %}


{% block body %}
    <div class="w3-display-middle" style="width:65%;">
        <div class="w3-bar w3-black">
            <button class="w3-bar-item w3-button tablink" onclick="openLink(event, 'Search');"><i
                        class="fa fa-train w3-margin-right"></i>Book
            </button>
            <button class="w3-bar-item w3-button tablink" onclick="openLink(event, 'Map');"><i
                        class="fa fa-map-marker w3-margin-right"></i>On Map
            </button>
            <form class="searchForm" action="{% url 'book:search' %}" method="post" onsubmit=submitSearchForm()>
                {% csrf_token %}
                <input class="w3-red w3-bar-item dateInput"  type="date" name="journey_date" style="float: right; width: 25%; height: 25px;"  required>
        </div>

        <!-- Tabs -->
        <div id="Search" class="w3-container w3-white w3-padding-16 myLink">
            <h3>Travel the world with us</h3>
                <div class="w3-row-padding" style="margin:0 -16px;">
                    <div class="w3-half">
                        <label>From</label>
                        <!--<input class="w3-input w3-border" type="text" placeholder="Departing from" name="source">-->
                        <input class="w3-input w3-border sourceInput" list="sources" name="source" required>
                          <datalist id="sources">
                              {% for s in stations %}
                              <option value="{{ s.pk }}">{{ s }}</option>
                              {% endfor %}
                          </datalist>
                    </div>
                    <div class="w3-half">
                        <label>To</label>
                        <!--<input class="w3-input w3-border" type="text" placeholder="Arriving at" name="dest">-->
                        <input class="w3-input w3-border" list="destinations" name="dest" required>
                          <datalist id="destinations">
                            {% for s in stations %}
                                <option value="{{ s.pk }}">{{ s }}</option>
                            {% endfor %}
                          </datalist>
                    </div>
                </div>
                <p>
                    <input class="w3-button w3-dark-grey" type="submit" value="Search Trains">
                </p>
            </form>
        </div>

        <div id="Map" class="w3-container w3-white w3-padding-16 myLink">
            <div id="map" style="width: 100%; height: 100%;"></div>
                <button href="{% url 'book:mapSearch' %}" class="mapSearch w3-button w3-dark-grey">Search Trains</button>


        </div>

    </div>
{% endblock %}

{% block end-scripts %}

    <script>
    var map; //Will contain map object.
    var marker_source = false; ////Has the user plotted their location marker?
    var marker_dest = false; ////Has the user plotted their location marker?
    var source_flag = true;
    var source,dest,date;
    var currentLocation,service;
    var i=0;
    //Function called to initialize / create the map.
    //This is called when the page has loaded.
    function initMap() {

        //The center location of our map.
        var centerOfMap = new google.maps.LatLng(16.482,73.339);

        //Map options.
        var options = {
          center: centerOfMap, //Set center.
          zoom: 6.54 //The zoom value.
        };

        //Create the map object.
        map = new google.maps.Map(document.getElementById('map'), options);

        //Listen for any clicks on the map.
        google.maps.event.addListener(map, 'click', function(event) {
            //Get the location that the user clicked.
            var clickedLocation = event.latLng;
            //If the marker hasn't been added.

            //Get the marker's location.
            if(source_flag) {
                if(marker_source === false){
                    //Create the marker.
                    marker_source = new google.maps.Marker({
                        position: clickedLocation,
                        map: map,
                        draggable: true,//make it draggable,
                        icon: {url: "http://maps.google.com/mapfiles/ms/icons/blue-dot.png"}
                    });
                    //Listen for drag events!
                    google.maps.event.addListener(marker_source, 'dragend', function(event){
                        markerLocation(marker_source);
                    });
                } else{
                    //Marker has already been added, so just change its location.
                    marker_source.setPosition(clickedLocation);
                }
                markerLocation(marker_source);
                source_flag=false;
            }
            else{
                if(marker_dest === false){
                    //Create the marker.
                    marker_dest = new google.maps.Marker({
                        position: clickedLocation,
                        map: map,
                        draggable: true ,//make it draggable,
                        icon: {url: "http://maps.google.com/mapfiles/ms/icons/purple-dot.png"}
                    });
                    //Listen for drag events!
                    google.maps.event.addListener(marker_dest, 'dragend', function(event){
                        markerLocation(marker_dest);
                    });
                } else{
                    //Marker has already been added, so just change its location.
                    marker_dest.setPosition(clickedLocation);
                }
                markerLocation(marker_dest);
                source_flag=true;
            }
        });
    }

    //This function will get the marker's current location and then add the lat/long
    //values to our textfields so that we can save the location.
    function markerLocation(marker){
        //Get location.
        currentLocation = marker.getPosition();
        console.log(currentLocation);
        console.log("hi");
        service = new google.maps.places.PlacesService(map);

        service.nearbySearch({
            location:currentLocation,
            radius:1000
        }, function(place, status) {
          if (status === google.maps.places.PlacesServiceStatus.OK) {
            google.maps.event.addListener(marker, 'click', function(){
                if(marker === marker_source){
                    source=place[0].name;
                }
                else{
                    dest=place[0].name;
                }
                date=$(".dateInput").val();
                console.log(source,dest,date)

            });
          }
        });
    }

    $('.mapSearch').click(function (e) {
        e.preventDefault();
        if (source && dest && date!="") {

            var url = $(this).attr('href');
            console.log(url);

            $.ajax({
                url: url,
                method: "GET",
                data: {
                    "source": source,
                    "dest": dest,
                    "date": date,
                },
                success: function (data) {
                    console.log(data);
                    query=$(".searchForm")[0];
                    query['source'].value=data.source;
                    query['dest'].value=data.dest;
                    query.submit();
                }, error: function (error) {
                    console.log(error);
                }
            });
        }
    });


    //Load the map when the page has finished loading.
    google.maps.event.addDomListener(window, 'load', initMap);
    </script>
<script>
    $(".dateInput").focus();

    function submitSearchForm()
    {
        <!--event.preventDefault();-->
        searchform = $(".searchForm")[0];
        console.log(searchform["source"]);
        searchForm.submit();
    }

    var source;
    var dest;

    // Tabs
    function openLink(evt, linkName) {
        var i, x, tablinks;
        x = document.getElementsByClassName("myLink");
        for (i = 0; i < x.length; i++) {
            x[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablink");
        for (i = 0; i < x.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" w3-red", "");
        }
        document.getElementById(linkName).style.display = "block";
        evt.currentTarget.className += " w3-red";
    }

    // Click on the first tablink on load
    document.getElementsByClassName("tablink")[0].click();


</script>
{% endblock %}

templates/book/trainSearch.html
{% extends "base.html" %}



{% block title %}{{ source }} to {{ dest }}{% endblock %}

{% block extra-head %}
    <style>
        .col {
            border-right: 1px solid #000;
            padding-right: 10px;
        }
    </style>
{% endblock %}

{% block body %}
<div class="w3-display-middle" style="width:65%">
    <div class="w3-container w3-white w3-padding-16"  style="height: 500px; overflow-y: scroll;">
    <ul>
        {% for train,sourceSchedule,destSchedule,scheduleCharts,fare in schedules %}
            <li class="col-sm-6 w3-card" style="width: 45%; height: 138px; margin: 2% 2.5%">
            <button class="w3-button showSeats" style="float:right; margin-top:1%; margin-right: -3%; ">Seats</button>
            <div class="trainDetails">
                <h6 style="font-weight: bold;">{{ train }}</h6>
                <table>
                    <tr style="line-height: 5%;"><th>Departure</th><td>{{ sourceSchedule.departure }}</td></tr>
                    <tr style="line-height: 5%;"><th>Arrival</th><td>{{ destSchedule.arrival }}</td></tr>
                </table>
            </div>
            <div class="seatDetails" style="display: none;">
                <div>
                    <table style="width: 50%; height: 100px;">
                        <thead><tr>
                            <th>Class</th>
                            <th>Seats</th>
                            <th>Fare</th>
                            <th>Class</th>
                            <th>Seats</th>
                            <th>Fare</th>
                        </tr></thead>
                        <tr style="line-height: 5%;">
                            <th><a href="{% url 'book:book' scheduleCharts.pk sourceSchedule.pk destSchedule.pk '1A' date %}">1A</a></th><td>{{ scheduleCharts.get1A }}</td>    <td class="col">₹{{ fare.1A }}</td>
                            <th><a href="{% url 'book:book' scheduleCharts.pk sourceSchedule.pk destSchedule.pk '2A' date %}">2A</a></th><td>{{ scheduleCharts.get2A }}</td>   <td>₹{{ fare.2A }}</td>
                        </tr>
                        <tr style="line-height: 5%;">
                            <th><a href="{% url 'book:book' scheduleCharts.pk sourceSchedule.pk destSchedule.pk '3A' date %}">3A</a></th><td>{{ scheduleCharts.get3A }}</td>   <td class="col">₹{{ fare.3A }}</td>
                            <th><a href="{% url 'book:book' scheduleCharts.pk sourceSchedule.pk destSchedule.pk 'SL' date %}">SL</a></th><td>{{ scheduleCharts.getSL }}</td>   <td>₹{{ fare.SL }}</td>
                        </tr>
                    </table>
                </div>
            </div>
            </li>
        {% endfor %}

    </ul>
    <div class="container">
        <h5 class="col-lg-12"  style=" text-align: center;"><a href="{% url 'book:complexSearch' source.pk dest.pk date %}" style="font-weight: bold; color: blue;">Click here</a> to check intermidiate trains</h5>
    </div>
    </div>

</div>
{% endblock %}

{% block end-scripts %}
    <script>
        $(".showSeats").click(function () {
            $(".seatDetails").hide();
            $(".trainDetails").show();
            if($(this).text()=="Trains"){
                $($(this).siblings(".seatDetails")[0]).hide();
                $($(this).siblings(".trainDetails")[0]).show();
                $(this).text("Seats");
            }
            else {
                $(".showSeats").text("Seats");
                $($(this).siblings(".seatDetails")[0]).show();
                $($(this).siblings(".trainDetails")[0]).hide();
                $(this).text("Trains");
            }
        });

    </script>


{% endblock %}