PseudoRCTC/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('book.urls')),
]

accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('password-change/', views.PasswordChangeView.as_view(),name='password-change'),
]

book/urls.py
from django.urls import path

from . import views

app_name = 'book'

urlpatterns = [
    path('',views.homeView,name="home"),
    path('search',views.searchView,name="search"),
    path('complexSearch/<source>-<dest>/<date>',views.complexSearchView,name="complexSearch"),
    path('mapSearch>',views.MapSearchView.as_view(),name="mapSearch"),
    path('book/<chart>/<sourceSchedule>-<destSchedule>/<type>/<date>',views.bookView,name="book"),
    path('book/<chart1>-<chart2>/<sourceSchedule>-<commonSchedule1>/<commonSchedule2>-<destSchedule>/<type>/<date>',views.complexBookView,name="complexBook"),
    path('confirm/<chart>/<sourceSchedule>-<destSchedule>/<type>/<date>',views.confirmTicketView,name="confirm"),
    path('confirm/<chart1>-<chart2>/<sourceSchedule>-<commonSchedule1>/<commonSchedule2>-<destSchedule>/<type>/<date>',views.complexConfirmTicketView,name="complexConfirm"),
    path('profile', views.profileView, name="profile"),
    path('cancel/<pk>', views.cancelTicket.as_view(), name="cancel"),


]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load staticfiles %}
    {% load static %}
    <title>{% block title %}PseudoRCTC{% endblock %}</title>
	<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
	<link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
	<link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
	<link href="{% static 'css/animate.css' %}" rel="stylesheet">
	<link href="{% static 'css/materialize.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="{% static 'js/jquery-3.3.1.js' %}"></script>
    <script src="{% static 'js/dateFormat.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/materialize.js' %}"></script>

{% block extra-head %}
{% endblock %}
</head>
<body class="w3-light-grey">

{% block navbar %}
<div class="w3-bar w3-white w3-border-bottom w3-xlarge">
    <a href="{% url 'book:home' %}" class="w3-bar-item w3-button w3-text-red w3-hover-red"><b><i
                    class="fa fa-map-marker w3-margin-right"></i>OuRCTC</b></a>
    {% block logout %}
        {% if request.user != "AnonymousUser" %}
            <a class="w3-bar-item w3-button w3-text-red w3-hover-red" href="{% url 'accounts:logout' %}" style="float: right;">
                <i class="fa fa-map-marker w3-margin-right fa-sign-out"></i>
            </a>
            <a class="w3-bar-item w3-button w3-text-red w3-hover-red" href="{% url 'book:profile' %}" style="float: right;">
                <i class="fa fa-map-marker w3-margin-right fa-users"></i></a>
        {% endif %}
    {% endblock %}
</div>
{% endblock %}

<img class="w3-image" src="{% static 'download.jpg' %}" alt="London" width="1500" height="700">
{% block body %}
{% endblock %}

{% block footer %}

{% endblock %}
{% block end-scripts %}
{% endblock %}

</body>
</html>